// svelte-image-search/src/App.svelte
<script>
  import getImages from "./api";

  let loading = false;
  let images = [];
  let searchTerm = "";

  async function handleSubmit(e) {
    e.preventDefault();

    loading = true;

    images = await getImages(searchTerm);

    loading = false;
  }
</script>

<style>
  .images {
    column-count: 3;
  }

  img {
    width: 100%;
  }

  @media (max-width: 1200px) {
    .images {
      column-count: 2;
    }
  }

  @media (max-width: 800px) {
    .images {
      column-count: 1;
    }
  }
</style>

<div class="app">
  <h1>Svelte Image Search</h1>
  <form on:submit={handleSubmit}>
    <label for="searchTerm">Search Term</label>
    <input
      class="u-full-width"
      type="text"
      id="searchTerm"
      name="searchTerm"
      bind:value={searchTerm} />
    <button type="submit">Search</button>
  </form>

  {#if loading}
    <img id="loadingImage" src="https://i.imgur.com/LVHmLnb.gif" />
  {/if}

  <section class="images">
    {#each images as image}
      <img src={image} />
    {/each}
  </section>
</div>

// vue-image-search/src/App.vue
<template>
  <div id="app">
    <h1>Vue Image Search</h1>
    <form @submit.prevent="formSubmitted">
      <label for="searchTerm">Search Term</label>
      <input
        class="u-full-width"
        type="text"
        id="searchTerm"
        name="searchTerm"
        v-model="searchTerm"
      />
      <button type="submit">Search</button>
    </form>
    <img
      v-if="loading"
      id="loadingImage"
      src="https://i.imgur.com/LVHmLnb.gif"
    />
    <section class="images">
      <img v-for="image in images" :key="image" :src="image" />
    </section>
  </div>
</template>

<script>
import getImages from './api'

export default {
  name: 'App',
  data: () => ({
    searchTerm: '',
    loading: false,
    images: [],
  }),
  methods: {
    async formSubmitted() {
      this.loading = true
      this.images = []
      this.images = await getImages(this.searchTerm)
      this.loading = false
    },
  },
}
</script>

<style>
body {
  width: 80%;
  margin: 2em auto 0 auto;
}

.images {
  column-count: 3;
}

img {
  width: 100%;
}

@media (max-width: 1200px) {
  .images {
    column-count: 2;
  }
}

@media (max-width: 800px) {
  .images {
    column-count: 1;
  }
}
</style>
