// svelte-image-search/src/App.svelte
<script>
  import getImages from "./api";

  let loading = false;
  let images = [];
  let searchTerm = "";

  async function handleSubmit(e) {
    e.preventDefault();

    loading = true;

    images = await getImages(searchTerm);

    loading = false;
  }
</script>

<style>
  .images {
    column-count: 3;
  }

  img {
    width: 100%;
  }

  @media (max-width: 1200px) {
    .images {
      column-count: 2;
    }
  }

  @media (max-width: 800px) {
    .images {
      column-count: 1;
    }
  }
</style>

<div class="app">
  <h1>Svelte Image Search</h1>
  <form on:submit={handleSubmit}>
    <label for="searchTerm">Search Term</label>
    <input
      class="u-full-width"
      type="text"
      id="searchTerm"
      name="searchTerm"
      bind:value={searchTerm} />
    <button type="submit">Search</button>
  </form>

  {#if loading}
    <img id="loadingImage" src="https://i.imgur.com/LVHmLnb.gif" />
  {/if}

  <section class="images">
    {#each images as image}
      <img src={image} />
    {/each}
  </section>
</div>

// react-image-search/src/App.js
import React from 'react'
import getImages from './api'

function App() {
  const [loading, setLoading] = React.useState(false)
  const [searchTerm, setSearchTerm] = React.useState('')
  const [images, setImages] = React.useState([])

  const handleSubmit = async (e) => {
    e.preventDefault()
    setLoading(true)
    setImages(await getImages(searchTerm))
    setLoading(false)
  }

  return (
    <div className="App">
      <h1>React Image Search</h1>
      <form onSubmit={handleSubmit}>
        <label htmlFor="searchTerm">Search Term</label>
        <input
          className="u-full-width"
          type="text"
          id="searchTerm"
          name="searchTerm"
          onChange={(e) => setSearchTerm(e.currentTarget.value)}
          value={searchTerm}
        />
        <button type="submit">Search</button>
      </form>
      {loading && (
        <img id="loadingImage" src="https://i.imgur.com/LVHmLnb.gif" />
      )}
      <section className="images">
        {images.map((image) => (
          <img key={image} src={image} />
        ))}
      </section>
    </div>
  )
}

export default App
